# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Gatsby Build
          command: npm run build
  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build:
    jobs
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
